#!/bin/bash

CONFIG_DIR="${HOME}/.config/sketchybar"
VARIABLES_DIR="${CONFIG_DIR}/variables"
ITEM_DIR="${CONFIG_DIR}/items"
PLUGIN_DIR="${CONFIG_DIR}/plugins"

source "${VARIABLES_DIR}/margins.sh"

source "${ITEM_DIR}/bar.sh"
source "${ITEM_DIR}/default.sh"

source "${ITEM_DIR}/spaces.sh"
source "${ITEM_DIR}/front_app.sh"
source "${ITEM_DIR}/clock.sh"

source "${ITEM_DIR}/battery.sh"
source "${ITEM_DIR}/wifi.sh"
source "${ITEM_DIR}/sound.sh"

source "${ITEM_DIR}/mirrored.sh"

source "${ITEM_DIR}/headphones.sh"
source "${ITEM_DIR}/music.sh"

source "${ITEM_DIR}/theme.sh"

sketchybar --update
