#!/usr/bin/env bash
#
# SketchyBar Configuration
# Copyright (C) 2024 Roger Steve Ruiz
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.


CONFIG_DIR="${HOME}/.files.nix/module/tools/sketchybar/config"

VARIABLES_DIR="${CONFIG_DIR}/variables"
ITEM_DIR="${CONFIG_DIR}/items"
PLUGIN_DIR="${CONFIG_DIR}/plugins"

source "${VARIABLES_DIR}/margins.sh"
source "${VARIABLES_DIR}/app_icons.sh"

source "${ITEM_DIR}/bar.sh"
source "${ITEM_DIR}/default.sh"

# La izquierda
source "${ITEM_DIR}/spaces.sh"
source "${ITEM_DIR}/clock.sh"

# El centro
source "${ITEM_DIR}/headphones.sh"
source "${ITEM_DIR}/front_app.sh"

# La derecha
source "${ITEM_DIR}/battery.sh"
source "${ITEM_DIR}/sound.sh"

source "${ITEM_DIR}/theme.sh"

sketchybar --update
