#!/usr/bin/env bash

# Custom post-merge
# Copyright (C) 2024 Roger Steve Ruiz
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

# Check for things that are changed. A file or directory can be checked and a
# message is printed out for the user to perform an action on.

set -eo pipefail

# If in CI exit immediately as this is only necessary for local development.
[[ "${CI:-}" == "true" ]] && exit 0

function changed {
  git diff --name-only 'HEAD@{1}' HEAD | grep "^$1" >/dev/null 2>&1
}

if changed 'migrations/'; then
  echo "🗄  The migrations/ directory has changed. You may want to run \`make db_dev_migrate\`."
fi
