# Alacritty configuration
# Copyright (C) 2024 Roger Steve Ruiz
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

live_config_reload = true

import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 15

[font.bold]
family = "RecMonoCasual Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "RecMonoCasual Nerd Font"
style = "Italic"

[font.normal]
family = "RecMonoCasual Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`¬]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 30000
multiplier = 1

[selection]
save_to_clipboard = true

[shell]
args = ["--exec", "/Users/yo/.local/bin/tux"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
opacity = 0.69
startup_mode = "Windowed"
title = "te vez bien hoy"
blur = true
option_as_alt = "OnlyRight"

[window.padding]
x = 0
y = 0
