# Starship configuration
# Copyright (C) 2024 Roger Steve Ruiz
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''$package$python$rust$nodejs$golang$terraform$ruby$nix_shell
$battery$directory$git_branch${custom.git_color}$git_metrics$git_status$git_state
$aws$jobs$cmd_duration$character$shell'''

palette = "dark"

[character]
success_symbol = "[ ](fg:green)"
error_symbol = "[ ](fg:red)"
vimcmd_symbol = "[ ](fg:blue)"
format = "[$symbol](fg:mauve)"

[cmd_duration]
min_time = 5_000
format = "[ ](fg:yellow)[($duration) ](italic fg:yellow)"

[package]
symbol = " "
display_private = true
format = "[$symbol](fg:peach)[$version ](italic fg:peach)"

[python]
symbol = " "
format = "[$symbol](fg:yellow)[$version ](italic fg:yellow)"

[rust]
symbol = " "
format = "[$symbol](fg:flamingo)[$version ](italic fg:flamingo)"

[nodejs]
symbol = "󰎙 "
format = "[$symbol](fg:green)[$version ](italic fg:green)"

[golang]
symbol = " "
format = "[$symbol](fg:sapphire)[$version ](italic fg:sapphire)"

[terraform]
symbol = "  "
detect_files = [".terraform-version"]
format = "[$symbol](fg:mauve)[$version ](italic fg:mauve)"

[ruby]
symbol = " "
format = "[$symbol](fg:red)[$version ](italic fg:red)"

[nix_shell]
symbol = "󱄅 "
impure_msg = '[   ](fg:base bg:sapphire)'
pure_msg = '[   ](fg:base bg:yellow)'
unknown_msg = '[   ](fg:base bg:red)'
format = "[$symbol](fg:sky)[$state]()[ $name ](italic fg:sky)"

[shell]
powershell_indicator = ''
nu_indicator = ''
zsh_indicator = ''
format = "[ $indicator ](fg:mauve) "
disabled = false

[aws]
symbol = "  "
expiration_symbol = ""
format = "[   ](bg:#ff9900 fg:base)[ $symbol](fg:#ff9900 bg:base)[ $profile ](bg:base fg:sapphire)[$region ](bg:base fg:sapphire) [$duration](italic fg:#ff9900)"

[aws.region_aliases]
us-gov-west-1 = "   us-gov-west-1"
us-gov-east-1 = "   us-gov-east-1"

[git_branch]
symbol = "  "
format = "[$symbol](fg:#f14e32)[$branch(:$remote_branch) ](italic fg:#f14e32)"

[git_status]
# NOTE: This is Git orange
format = "([](#f14e32) [$all_status$ahead_behind]($style) )"
modified = "[](blue) "
staged = "[](green) "
deleted = "[](red) "
renamed = "[](peach) "
untracked = "[󰡯](yellow) "
diverged = "[](maroon)"
ahead = "[](green) "
behind = "[](flamingo) "
conflicted = "[](yellow) "
stashed = "[󰘓](magenta) "

[git_metrics]
format = " ([ $added]($added_style) )([ $deleted]($deleted_style) )"
disabled = false

#  
# ▓
# ▒
# ░

[directory]
truncation_length = 5
truncation_symbol = "󰃕 "
home_symbol = "~"
style = "bold fg:green"

# NOTE: This hex-value is Git orange from their website. Este valor hex es
# naranja del website de Git.
repo_root_style = "bold fg:#f14e32"

read_only = " "
read_only_style = "fg:pink"

truncate_to_repo = true
format = "[ ](fg:green bold)[ $path ]($style)[$read_only]($read_only_style)"
repo_root_format = "[ ](fg:green)[ $before_root_path]($repo_root_style)[$repo_root[$path](dimmed fg:sky)]($repo_root_style)[$read_only]($read_only_style)"

[jobs]
symbol = " "
style = "fg:pink"
format = "[$symbol]($style)[$number](fg:pink)"

[time]
disabled = false
time_format = "%T"
format = "[ 󰥔 ](fg:yellow)[$time ](italic fg:yellow)"
utc_time_offset = "local"

[custom.git_color]
command = ''' perl -e 'foreach $a(@ARGV){print "\e[48;2;".join(";",unpack("C*",pack("H*",$a)))."m  \e[49m"}; print " #@ARGV";' $(git rev-parse HEAD | head -c 6) 2>/dev/null '''
when = 'git rev-parse --is-inside-work-tree'
description = "The current hexidecimal color based on the current Git SHA at HEAD."
unsafe_no_escape = true
style = "bold italic fg:subtext1"

[palettes.light]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.dark]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
