# Zsh configuration
# Copyright (C) 2024 Roger Steve Ruiz
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

# eval "$(nodenv init -)"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
eval "$(op completion zsh)"; compdef _op op

unsetopt correct_all
export VISUAL=nvim
autoload edit-command-line; zle -N edit-command-line
set -o vi
bindkey "\e[1;5D" backward-word
bindkey "\e[1;5C" forward-word
bindkey -M vicmd ' ' edit-command-line
bindkey '^[[Z' reverse-menu-complete

ulimit -n 10000

export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

export PATH="/usr/local/bin:$PATH"

export GOPATH=${GOPATH:-$(go env GOPATH)}

export PATH=$(go env GOPATH)/bin:$PATH

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

[ -s "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

[ -s "$HOME/.deno/env" ] && source "$HOME/.deno/env"

source "$HOME/.local/share/rstrz/.variables"
source "$HOME/.local/share/rstrz/.functions"

# WARN: deno https://github.com/denoland/deno_install/blob/b4dad3254e44fbad38f7a4859e7840342cdba2b9/shell-setup/src/shell.ts#L197-L220
#
# Add deno completions to search path
if [[ ":$FPATH:" != *":/Users/yo/.zsh/completions/_deno.zsh:"* ]]; then
  export FPATH="/Users/yo/.zsh/completions/_deno.zsh:$FPATH"
fi
