# eval "$(nodenv init -)"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
eval "$(op completion zsh)"; compdef _op op

unsetopt correct_all
export VISUAL=nvim
autoload edit-command-line; zle -N edit-command-line
set -o vi
bindkey "\e[1;5D" backward-word
bindkey "\e[1;5C" forward-word
bindkey -M vicmd ' ' edit-command-line
bindkey '^[[Z' reverse-menu-complete

ulimit -n 10000

export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

export PATH="/usr/local/bin:$PATH"

export GOPATH=${GOPATH:-$(go env GOPATH)}

export PATH=$(go env GOPATH)/bin:$PATH

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
[ -s "/Users/yo/.bun/_bun" ] && source "/Users/yo/.bun/_bun"

[ -s "/Users/yo/.cargo/env" ] && source "$HOME/.cargo/env"

source "$HOME/.local/share/rstrz/.variables"
source "$HOME/.local/share/rstrz/.functions"
