name: 'Repo Lockdown'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
  schedule:
    - cron: '20 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    name: Imponer clausura de'l repositorio
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
